---
title: "Gruesa 2014 2024"
format: html
editor: visual
---

```{r}
#| message: false
#| warning: false
#| include: false
#| paged-print: false
library(tidyverse)
```
```{r}
gruesa<-tibble::tribble(
              ~Cultivo,  ~Campania, ~Provincia, ~Departamento, ~Sup_Sembrada_Ha, ~Sup_Cosechada_Ha, ~Produccion_Tn, ~Rendimiento_KgHa,
             "Girasol", "2014/15", "LA PAMPA",     "ATREUCÓ",                45000L,                 44600L,             84740L,                  1900L,
             "Girasol", "2015/16", "LA PAMPA",     "ATREUCÓ",                40000L,                 40000L,             80000L,                  2000L,
             "Girasol", "2016/17", "LA PAMPA",     "ATREUCÓ",                42000L,                 42000L,             79800L,                  1900L,
             "Girasol", "2017/18", "LA PAMPA",     "ATREUCÓ",                33600L,                 33600L,             84000L,                  2500L,
             "Girasol", "2018/19", "LA PAMPA",     "ATREUCÓ",                18300L,                 18300L,             43920L,                  2400L,
             "Girasol", "2019/20", "LA PAMPA",     "ATREUCÓ",                15000L,                 15000L,             30000L,                  2000L,
             "Girasol", "2020/21", "LA PAMPA",     "ATREUCÓ",                19430L,                 19430L,             42746L,                  2200L,
             "Girasol", "2021/22", "LA PAMPA",     "ATREUCÓ",                41562L,                 41562L,            103904L,                  2500L,
             "Girasol", "2022/23", "LA PAMPA",     "ATREUCÓ",                49650L,                 49650L,            124125L,                  2500L,
             "Girasol", "2023/24", "LA PAMPA",     "ATREUCÓ",                26200L,                 26200L,             62880L,                  2400L,
             "Girasol", "2014/15", "LA PAMPA",     "CAPITAL",                25000L,                 24700L,             44460L,                  1800L,
             "Girasol", "2015/16", "LA PAMPA",     "CAPITAL",                20000L,                 20000L,             36000L,                  1800L,
             "Girasol", "2016/17", "LA PAMPA",     "CAPITAL",                22000L,                 22000L,             41800L,                  1900L,
             "Girasol", "2017/18", "LA PAMPA",     "CAPITAL",                17100L,                 17100L,             34200L,                  2000L,
             "Girasol", "2018/19", "LA PAMPA",     "CAPITAL",                21000L,                 21000L,             48300L,                  2300L,
             "Girasol", "2019/20", "LA PAMPA",     "CAPITAL",                15400L,                 15400L,             27720L,                  1800L,
             "Girasol", "2020/21", "LA PAMPA",     "CAPITAL",                15000L,                 15000L,             30000L,                  2000L,
             "Girasol", "2021/22", "LA PAMPA",     "CAPITAL",                14768L,                 14768L,             32490L,                  2200L,
             "Girasol", "2022/23", "LA PAMPA",     "CAPITAL",                18200L,                 18200L,             40040L,                  2200L,
             "Girasol", "2023/24", "LA PAMPA",     "CAPITAL",                19200L,                 19200L,             42240L,                  2200L,
             "Girasol", "2014/15", "LA PAMPA",     "CATRILÓ",                60000L,                 59500L,            119000L,                  2000L,
             "Girasol", "2015/16", "LA PAMPA",     "CATRILÓ",                55000L,                 55000L,            132000L,                  2400L,
             "Girasol", "2016/17", "LA PAMPA",     "CATRILÓ",                57000L,                 57000L,            125400L,                  2200L,
             "Girasol", "2017/18", "LA PAMPA",     "CATRILÓ",                44100L,                 44100L,            123480L,                  2800L,
             "Girasol", "2018/19", "LA PAMPA",     "CATRILÓ",                35800L,                 35800L,             85920L,                  2400L,
             "Girasol", "2019/20", "LA PAMPA",     "CATRILÓ",                27750L,                 27750L,             61050L,                  2200L,
             "Girasol", "2020/21", "LA PAMPA",     "CATRILÓ",                30000L,                 30000L,             75000L,                  2500L,
             "Girasol", "2021/22", "LA PAMPA",     "CATRILÓ",                34330L,                 34330L,             96123L,                  2800L,
             "Girasol", "2022/23", "LA PAMPA",     "CATRILÓ",                49400L,                 49400L,            138320L,                  2800L,
             "Girasol", "2023/24", "LA PAMPA",     "CATRILÓ",                34300L,                 34300L,             85750L,                  2500L,
             "Girasol", "2014/15", "LA PAMPA",  "CHAPALEUFÚ",                26800L,                 26300L,             76270L,                  2900L,
             "Girasol", "2015/16", "LA PAMPA",  "CHAPALEUFÚ",                21400L,                 20500L,             46690L,                  2278L,
             "Girasol", "2016/17", "LA PAMPA",  "CHAPALEUFÚ",                 6500L,                  6300L,             15120L,                  2400L,
             "Girasol", "2017/18", "LA PAMPA",  "CHAPALEUFÚ",                 5900L,                  5700L,             15960L,                  2800L,
             "Girasol", "2018/19", "LA PAMPA",  "CHAPALEUFÚ",                  400L,                   400L,               800L,                  2000L,
             "Girasol", "2019/20", "LA PAMPA",  "CHAPALEUFÚ",                 4000L,                  3900L,              9400L,                  2410L,
             "Girasol", "2020/21", "LA PAMPA",  "CHAPALEUFÚ",                 5400L,                  5300L,             13250L,                  2500L,
             "Girasol", "2021/22", "LA PAMPA",  "CHAPALEUFÚ",                 7258L,                  6858L,             17145L,                  2500L,
             "Girasol", "2022/23", "LA PAMPA",  "CHAPALEUFÚ",                12700L,                 12400L,             27280L,                  2200L,
             "Girasol", "2023/24", "LA PAMPA",  "CHAPALEUFÚ",                 9700L,                  9500L,             23750L,                  2500L,
             "Girasol", "2014/15", "LA PAMPA",     "CONHELO",                 2800L,                  2700L,              6750L,                  2500L,
             "Girasol", "2015/16", "LA PAMPA",     "CONHELO",                 2800L,                  2700L,              4590L,                  1700L,
             "Girasol", "2016/17", "LA PAMPA",     "CONHELO",                 4500L,                  4300L,              9890L,                  2300L,
             "Girasol", "2017/18", "LA PAMPA",     "CONHELO",                 3600L,                  3500L,              7700L,                  2200L,
             "Girasol", "2018/19", "LA PAMPA",     "CONHELO",                 9500L,                  9300L,             20460L,                  2200L,
             "Girasol", "2019/20", "LA PAMPA",     "CONHELO",                 3400L,                  3300L,              7300L,                  2212L,
             "Girasol", "2020/21", "LA PAMPA",     "CONHELO",                 8100L,                  7700L,             13860L,                  1800L,
             "Girasol", "2021/22", "LA PAMPA",     "CONHELO",                 7481L,                  7281L,             16746L,                  2300L,
             "Girasol", "2022/23", "LA PAMPA",     "CONHELO",                25400L,                 24900L,             44820L,                  1800L,
             "Girasol", "2023/24", "LA PAMPA",     "CONHELO",                30100L,                 28600L,             62920L,                  2200L,
             "Girasol", "2020/21", "LA PAMPA",   "GUATRACHÉ",                  500L,                   500L,              1000L,                  2000L,
             "Girasol", "2021/22", "LA PAMPA",   "GUATRACHÉ",                  400L,                   400L,               720L,                  1800L,
             "Girasol", "2022/23", "LA PAMPA",   "GUATRACHÉ",                  500L,                   500L,               900L,                  1800L,
             "Girasol", "2020/21", "LA PAMPA",       "HUCAL",                  160L,                   160L,               288L,                  1800L,
             "Girasol", "2021/22", "LA PAMPA",       "HUCAL",                  200L,                   200L,               300L,                  1500L,
             "Girasol", "2022/23", "LA PAMPA",       "HUCAL",                  500L,                   500L,               750L,                  1500L,
             "Girasol", "2014/15", "LA PAMPA",      "MARACÓ",                17200L,                 16900L,             49010L,                  2900L,
             "Girasol", "2015/16", "LA PAMPA",      "MARACÓ",                15500L,                 14800L,             32340L,                  2185L,
             "Girasol", "2016/17", "LA PAMPA",      "MARACÓ",                13000L,                 12600L,             30240L,                  2400L,
             "Girasol", "2017/18", "LA PAMPA",      "MARACÓ",                11700L,                 11300L,             30510L,                  2700L,
             "Girasol", "2018/19", "LA PAMPA",      "MARACÓ",                12900L,                 12500L,             25000L,                  2000L,
             "Girasol", "2019/20", "LA PAMPA",      "MARACÓ",                 8600L,                  8400L,             20200L,                  2405L,
             "Girasol", "2020/21", "LA PAMPA",      "MARACÓ",                20300L,                 19900L,             49750L,                  2500L,
             "Girasol", "2021/22", "LA PAMPA",      "MARACÓ",                19903L,                 19003L,             47507L,                  2500L,
             "Girasol", "2022/23", "LA PAMPA",      "MARACÓ",                18300L,                 17900L,             39380L,                  2200L,
             "Girasol", "2023/24", "LA PAMPA",      "MARACÓ",                17200L,                 16900L,             42250L,                  2500L,
             "Girasol", "2014/15", "LA PAMPA", "QUEMÚ QUEMÚ",                37700L,                 36900L,             88560L,                  2400L,
             "Girasol", "2015/16", "LA PAMPA", "QUEMÚ QUEMÚ",                37700L,                 36500L,             72400L,                  1984L,
             "Girasol", "2016/17", "LA PAMPA", "QUEMÚ QUEMÚ",                39700L,                 38500L,             92400L,                  2400L,
             "Girasol", "2017/18", "LA PAMPA", "QUEMÚ QUEMÚ",                35700L,                 34600L,             89960L,                  2600L,
             "Girasol", "2018/19", "LA PAMPA", "QUEMÚ QUEMÚ",                26600L,                 26100L,             60030L,                  2300L,
             "Girasol", "2019/20", "LA PAMPA", "QUEMÚ QUEMÚ",                13400L,                 13100L,             28800L,                  2198L,
             "Girasol", "2020/21", "LA PAMPA", "QUEMÚ QUEMÚ",                29900L,                 29300L,             67390L,                  2300L,
             "Girasol", "2021/22", "LA PAMPA", "QUEMÚ QUEMÚ",                29067L,                 27667L,             66402L,                  2400L,
             "Girasol", "2022/23", "LA PAMPA", "QUEMÚ QUEMÚ",                38200L,                 37400L,             82280L,                  2200L,
             "Girasol", "2023/24", "LA PAMPA", "QUEMÚ QUEMÚ",                25000L,                 24500L,             61250L,                  2500L,
             "Girasol", "2014/15", "LA PAMPA",      "RANCUL",                14000L,                 13300L,             33250L,                  2500L,
             "Girasol", "2015/16", "LA PAMPA",      "RANCUL",                12600L,                 12000L,             24000L,                  2000L,
             "Girasol", "2016/17", "LA PAMPA",      "RANCUL",                 9700L,                  9200L,             20240L,                  2200L,
             "Girasol", "2017/18", "LA PAMPA",      "RANCUL",                 7800L,                  7600L,             18240L,                  2400L,
             "Girasol", "2018/19", "LA PAMPA",      "RANCUL",                10700L,                 10500L,             23100L,                  2200L,
             "Girasol", "2019/20", "LA PAMPA",      "RANCUL",                 9000L,                  8800L,             20200L,                  2295L,
             "Girasol", "2020/21", "LA PAMPA",      "RANCUL",                11600L,                 11000L,             22000L,                  2000L,
             "Girasol", "2021/22", "LA PAMPA",      "RANCUL",                17752L,                 17352L,             39910L,                  2300L,
             "Girasol", "2022/23", "LA PAMPA",      "RANCUL",                21600L,                 21200L,             38160L,                  1800L,
             "Girasol", "2023/24", "LA PAMPA",      "RANCUL",                12000L,                 11400L,             26220L,                  2300L,
             "Girasol", "2014/15", "LA PAMPA",     "REALICÓ",                 8900L,                  8500L,             22950L,                  2700L,
             "Girasol", "2015/16", "LA PAMPA",     "REALICÓ",                 8000L,                  7600L,             15200L,                  2000L,
             "Girasol", "2016/17", "LA PAMPA",     "REALICÓ",                 3500L,                  3300L,              7590L,                  2300L,
             "Girasol", "2017/18", "LA PAMPA",     "REALICÓ",                 7100L,                  6900L,             16560L,                  2400L,
             "Girasol", "2018/19", "LA PAMPA",     "REALICÓ",                13700L,                 13300L,             30590L,                  2300L,
             "Girasol", "2019/20", "LA PAMPA",     "REALICÓ",                12800L,                 12500L,             28800L,                  2304L,
             "Girasol", "2020/21", "LA PAMPA",     "REALICÓ",                 8500L,                  8300L,             16600L,                  2000L,
             "Girasol", "2021/22", "LA PAMPA",     "REALICÓ",                16244L,                 15644L,             39111L,                  2500L,
             "Girasol", "2022/23", "LA PAMPA",     "REALICÓ",                26000L,                 25500L,             51000L,                  2000L,
             "Girasol", "2023/24", "LA PAMPA",     "REALICÓ",                24600L,                 24100L,             55430L,                  2300L,
             "Girasol", "2014/15", "LA PAMPA",        "TOAY",                10000L,                  9800L,             12740L,                  1300L,
             "Girasol", "2015/16", "LA PAMPA",        "TOAY",                 9000L,                  9000L,             14400L,                  1600L,
             "Girasol", "2016/17", "LA PAMPA",        "TOAY",                 8000L,                  8000L,             12800L,                  1600L,
             "Girasol", "2017/18", "LA PAMPA",        "TOAY",                 5600L,                  5600L,              8400L,                  1500L,
             "Girasol", "2018/19", "LA PAMPA",        "TOAY",                 2900L,                  2900L,              4350L,                  1500L,
             "Girasol", "2019/20", "LA PAMPA",        "TOAY",                 2200L,                  2200L,              2860L,                  1300L,
             "Girasol", "2020/21", "LA PAMPA",        "TOAY",                 2000L,                  2000L,              3000L,                  1500L,
             "Girasol", "2021/22", "LA PAMPA",        "TOAY",                14155L,                 14155L,             21232L,                  1500L,
             "Girasol", "2022/23", "LA PAMPA",        "TOAY",                 4150L,                  4150L,              6225L,                  1500L,
             "Girasol", "2023/24", "LA PAMPA",        "TOAY",                12700L,                 12700L,             15240L,                  1200L,
             "Girasol", "2014/15", "LA PAMPA",      "TRENEL",                 2200L,                  2100L,              5040L,                  2400L,
             "Girasol", "2015/16", "LA PAMPA",      "TRENEL",                 2000L,                  1900L,              3420L,                  1800L,
             "Girasol", "2016/17", "LA PAMPA",      "TRENEL",                 3400L,                  3300L,              7260L,                  2200L,
             "Girasol", "2017/18", "LA PAMPA",      "TRENEL",                 2700L,                  2600L,              5720L,                  2200L,
             "Girasol", "2018/19", "LA PAMPA",      "TRENEL",                 5700L,                  5600L,             11760L,                  2100L,
             "Girasol", "2019/20", "LA PAMPA",      "TRENEL",                 1900L,                  1900L,              4400L,                  2316L,
             "Girasol", "2020/21", "LA PAMPA",      "TRENEL",                 3100L,                  2900L,              5510L,                  1900L,
             "Girasol", "2021/22", "LA PAMPA",      "TRENEL",                 5494L,                  5394L,             12405L,                  2300L,
             "Girasol", "2022/23", "LA PAMPA",      "TRENEL",                17000L,                 16700L,             30060L,                  1800L,
             "Girasol", "2023/24", "LA PAMPA",      "TRENEL",                13900L,                 13200L,             29040L,                  2200L,
             "Girasol", "2014/15", "LA PAMPA",     "UTRACÁN",                 7000L,                  6900L,              8280L,                  1200L,
             "Girasol", "2015/16", "LA PAMPA",     "UTRACÁN",                 6000L,                  6000L,             10200L,                  1700L,
             "Girasol", "2016/17", "LA PAMPA",     "UTRACÁN",                 3000L,                  3000L,              4800L,                  1600L,
             "Girasol", "2017/18", "LA PAMPA",     "UTRACÁN",                 3000L,                  3000L,              4500L,                  1500L,
             "Girasol", "2020/21", "LA PAMPA",     "UTRACÁN",                   90L,                    90L,               135L,                  1500L,
             "Girasol", "2021/22", "LA PAMPA",     "UTRACÁN",                  300L,                   300L,               450L,                  1500L,
             "Girasol", "2022/23", "LA PAMPA",     "UTRACÁN",                  300L,                   300L,               450L,                  1500L,
             "Girasol", "2023/24", "LA PAMPA",     "UTRACÁN",                 1600L,                  1600L,              1920L,                  1200L,
                "Maíz", "2014/15", "LA PAMPA",     "ATREUCÓ",                26000L,                 13000L,             50700L,                  3900L,
                "Maíz", "2015/16", "LA PAMPA",     "ATREUCÓ",                55000L,                 30400L,            164160L,                  5400L,
                "Maíz", "2016/17", "LA PAMPA",     "ATREUCÓ",                36500L,                 25000L,             90000L,                  3600L,
                "Maíz", "2017/18", "LA PAMPA",     "ATREUCÓ",                35100L,                 19200L,             67200L,                  3500L,
                "Maíz", "2018/19", "LA PAMPA",     "ATREUCÓ",                36150L,                 23490L,            131544L,                  5600L,
                "Maíz", "2019/20", "LA PAMPA",     "ATREUCÓ",                37900L,                 17600L,            103840L,                  5900L,
                "Maíz", "2020/21", "LA PAMPA",     "ATREUCÓ",                51300L,                 46170L,            267786L,                  5800L,
                "Maíz", "2021/22", "LA PAMPA",     "ATREUCÓ",                53600L,                 45100L,            248050L,                  5500L,
                "Maíz", "2022/23", "LA PAMPA",     "ATREUCÓ",                57000L,                 51300L,            282150L,                  5500L,
                "Maíz", "2023/24", "LA PAMPA",     "ATREUCÓ",                79500L,                 71540L,            393470L,                  5500L,
                "Maíz", "2014/15", "LA PAMPA",     "CAPITAL",                21000L,                  9000L,             30600L,                  3400L,
                "Maíz", "2015/16", "LA PAMPA",     "CAPITAL",                45000L,                 24100L,            127730L,                  5300L,
                "Maíz", "2016/17", "LA PAMPA",     "CAPITAL",                22500L,                 16000L,             73600L,                  4600L,
                "Maíz", "2017/18", "LA PAMPA",     "CAPITAL",                20600L,                 11280L,             39480L,                  3500L,
                "Maíz", "2018/19", "LA PAMPA",     "CAPITAL",                27700L,                 11416L,             59363L,                  5200L,
                "Maíz", "2019/20", "LA PAMPA",     "CAPITAL",                26100L,                  8500L,             45900L,                  5400L,
                "Maíz", "2020/21", "LA PAMPA",     "CAPITAL",                25500L,                 16240L,             86072L,                  5300L,
                "Maíz", "2021/22", "LA PAMPA",     "CAPITAL",                52100L,                 33200L,            166000L,                  5000L,
                "Maíz", "2022/23", "LA PAMPA",     "CAPITAL",                39800L,                 25273L,            126365L,                  5000L,
                "Maíz", "2023/24", "LA PAMPA",     "CAPITAL",                45200L,                 28700L,            143500L,                  5000L,
                "Maíz", "2014/15", "LA PAMPA",     "CATRILÓ",                29000L,                  4000L,             18000L,                  4500L,
                "Maíz", "2015/16", "LA PAMPA",     "CATRILÓ",                51000L,                 30100L,            174580L,                  5800L,
                "Maíz", "2016/17", "LA PAMPA",     "CATRILÓ",                30000L,                 19200L,             97920L,                  5100L,
                "Maíz", "2017/18", "LA PAMPA",     "CATRILÓ",                42500L,                 30460L,            152300L,                  5000L,
                "Maíz", "2018/19", "LA PAMPA",     "CATRILÓ",                38900L,                 33740L,            199066L,                  5900L,
                "Maíz", "2019/20", "LA PAMPA",     "CATRILÓ",                47300L,                 33700L,            205570L,                  6100L,
                "Maíz", "2020/21", "LA PAMPA",     "CATRILÓ",                47100L,                 41000L,            246000L,                  6000L,
                "Maíz", "2021/22", "LA PAMPA",     "CATRILÓ",                71700L,                 62600L,            406900L,                  6500L,
                "Maíz", "2022/23", "LA PAMPA",     "CATRILÓ",                52700L,                 45956L,            252758L,                  5500L,
                "Maíz", "2023/24", "LA PAMPA",     "CATRILÓ",                64600L,                 56330L,            309815L,                  5500L,
                "Maíz", "2014/15", "LA PAMPA",  "CHAPALEUFÚ",                35000L,                 18000L,            171000L,                  9500L,
                "Maíz", "2015/16", "LA PAMPA",  "CHAPALEUFÚ",                44400L,                 35620L,            341952L,                  9600L,
                "Maíz", "2016/17", "LA PAMPA",  "CHAPALEUFÚ",                46300L,                 17300L,            162620L,                  9400L,
                "Maíz", "2017/18", "LA PAMPA",  "CHAPALEUFÚ",                43300L,                 36590L,            285402L,                  7800L,
                "Maíz", "2018/19", "LA PAMPA",  "CHAPALEUFÚ",                56000L,                 42730L,            397389L,                  9300L,
                "Maíz", "2019/20", "LA PAMPA",  "CHAPALEUFÚ",                64000L,                 37780L,            351918L,                  9315L,
                "Maíz", "2020/21", "LA PAMPA",  "CHAPALEUFÚ",                56600L,                 49100L,            412440L,                  8400L,
                "Maíz", "2021/22", "LA PAMPA",  "CHAPALEUFÚ",                64700L,                 54600L,            475102L,                  8702L,
                "Maíz", "2022/23", "LA PAMPA",  "CHAPALEUFÚ",                64700L,                 54700L,            419549L,                  7670L,
                "Maíz", "2023/24", "LA PAMPA",  "CHAPALEUFÚ",                46800L,                 43200L,            374112L,                  8660L,
                "Maíz", "2014/15", "LA PAMPA",     "CONHELO",                40000L,                 11000L,             55000L,                  5000L,
                "Maíz", "2015/16", "LA PAMPA",     "CONHELO",                58500L,                 21940L,            149192L,                  6800L,
                "Maíz", "2016/17", "LA PAMPA",     "CONHELO",                41000L,                  6000L,             43800L,                  7300L,
                "Maíz", "2017/18", "LA PAMPA",     "CONHELO",                42900L,                 25150L,            163475L,                  6500L,
                "Maíz", "2018/19", "LA PAMPA",     "CONHELO",                42000L,                  5120L,             39578L,                  7730L,
                "Maíz", "2019/20", "LA PAMPA",     "CONHELO",                43100L,                 25822L,            214542L,                  8309L,
                "Maíz", "2020/21", "LA PAMPA",     "CONHELO",                73000L,                 51800L,            305620L,                  5900L,
                "Maíz", "2021/22", "LA PAMPA",     "CONHELO",                89400L,                 64300L,            392301L,                  6101L,
                "Maíz", "2022/23", "LA PAMPA",     "CONHELO",                84700L,                 52300L,            339427L,                  6490L,
                "Maíz", "2023/24", "LA PAMPA",     "CONHELO",                90700L,                 67100L,            461648L,                  6880L,
                "Maíz", "2014/15", "LA PAMPA",   "GUATRACHÉ",                11000L,                  3000L,              9000L,                  3000L,
                "Maíz", "2015/16", "LA PAMPA",   "GUATRACHÉ",                35000L,                 19650L,             94320L,                  4800L,
                "Maíz", "2016/17", "LA PAMPA",   "GUATRACHÉ",                12500L,                  4200L,             13020L,                  3100L,
                "Maíz", "2017/18", "LA PAMPA",   "GUATRACHÉ",                16800L,                  9190L,             27570L,                  3000L,
                "Maíz", "2018/19", "LA PAMPA",   "GUATRACHÉ",                18100L,                  1300L,              3770L,                  2900L,
                "Maíz", "2019/20", "LA PAMPA",   "GUATRACHÉ",                17700L,                  3700L,             11470L,                  3100L,
                "Maíz", "2020/21", "LA PAMPA",   "GUATRACHÉ",                17000L,                  6600L,             23100L,                  3500L,
                "Maíz", "2021/22", "LA PAMPA",   "GUATRACHÉ",                27500L,                  8200L,             32800L,                  4000L,
                "Maíz", "2022/23", "LA PAMPA",   "GUATRACHÉ",                17300L,                  6936L,             27744L,                  4000L,
                "Maíz", "2023/24", "LA PAMPA",   "GUATRACHÉ",                23300L,                  9350L,             37400L,                  4000L,
                "Maíz", "2014/15", "LA PAMPA",       "HUCAL",                 6000L,                  2000L,              6000L,                  3000L,
                "Maíz", "2015/16", "LA PAMPA",       "HUCAL",                 6000L,                  2300L,              7590L,                  3300L,
                "Maíz", "2016/17", "LA PAMPA",       "HUCAL",                 9500L,                  3500L,              9100L,                  2600L,
                "Maíz", "2017/18", "LA PAMPA",       "HUCAL",                11400L,                  6740L,             13480L,                  2000L,
                "Maíz", "2018/19", "LA PAMPA",       "HUCAL",                 4500L,                   700L,              2030L,                  2900L,
                "Maíz", "2019/20", "LA PAMPA",       "HUCAL",                 7600L,                   900L,              2790L,                  3100L,
                "Maíz", "2020/21", "LA PAMPA",       "HUCAL",                 7100L,                   900L,              3150L,                  3500L,
                "Maíz", "2021/22", "LA PAMPA",       "HUCAL",                10500L,                  4300L,             15050L,                  3500L,
                "Maíz", "2022/23", "LA PAMPA",       "HUCAL",                 4500L,                   540L,              1890L,                  3500L,
                "Maíz", "2023/24", "LA PAMPA",       "HUCAL",                41000L,                  4900L,             17150L,                  3500L,
                "Maíz", "2014/15", "LA PAMPA",      "MARACÓ",                40800L,                 20800L,            197600L,                  9500L,
                "Maíz", "2015/16", "LA PAMPA",      "MARACÓ",                55500L,                 34680L,            332928L,                  9600L,
                "Maíz", "2016/17", "LA PAMPA",      "MARACÓ",                62900L,                 24900L,            234060L,                  9400L,
                "Maíz", "2017/18", "LA PAMPA",      "MARACÓ",                48000L,                 19550L,            146625L,                  7500L,
                "Maíz", "2018/19", "LA PAMPA",      "MARACÓ",                53000L,                 28940L,            266248L,                  9200L,
                "Maíz", "2019/20", "LA PAMPA",      "MARACÓ",                59300L,                 34966L,            329702L,                  9429L,
                "Maíz", "2020/21", "LA PAMPA",      "MARACÓ",                46600L,                 37500L,            311250L,                  8300L,
                "Maíz", "2021/22", "LA PAMPA",      "MARACÓ",                57400L,                 45100L,            375800L,                  8333L,
                "Maíz", "2022/23", "LA PAMPA",      "MARACÓ",                48100L,                 30700L,            238846L,                  7780L,
                "Maíz", "2023/24", "LA PAMPA",      "MARACÓ",                57900L,                 48000L,            420000L,                  8750L,
                "Maíz", "2014/15", "LA PAMPA", "QUEMÚ QUEMÚ",                40000L,                 13000L,            117000L,                  9000L,
                "Maíz", "2015/16", "LA PAMPA", "QUEMÚ QUEMÚ",                66800L,                 32980L,            306714L,                  9300L,
                "Maíz", "2016/17", "LA PAMPA", "QUEMÚ QUEMÚ",                52800L,                 26300L,            220920L,                  8400L,
                "Maíz", "2017/18", "LA PAMPA", "QUEMÚ QUEMÚ",                55900L,                 25080L,            188100L,                  7500L,
                "Maíz", "2018/19", "LA PAMPA", "QUEMÚ QUEMÚ",                53000L,                 24270L,            218430L,                  9000L,
                "Maíz", "2019/20", "LA PAMPA", "QUEMÚ QUEMÚ",                59500L,                 35790L,            335631L,                  9378L,
                "Maíz", "2020/21", "LA PAMPA", "QUEMÚ QUEMÚ",                47400L,                 26200L,            206980L,                  7900L,
                "Maíz", "2021/22", "LA PAMPA", "QUEMÚ QUEMÚ",                72100L,                 58300L,            492099L,                  8441L,
                "Maíz", "2022/23", "LA PAMPA", "QUEMÚ QUEMÚ",                54300L,                 43300L,            340338L,                  7860L,
                "Maíz", "2023/24", "LA PAMPA", "QUEMÚ QUEMÚ",                73600L,                 62600L,            455728L,                  7280L,
                "Maíz", "2014/15", "LA PAMPA",      "RANCUL",                29000L,                  8000L,             48000L,                  6000L,
                "Maíz", "2015/16", "LA PAMPA",      "RANCUL",                52100L,                 16380L,            127764L,                  7800L,
                "Maíz", "2016/17", "LA PAMPA",      "RANCUL",                48200L,                  7700L,             63140L,                  8200L,
                "Maíz", "2017/18", "LA PAMPA",      "RANCUL",                51800L,                 17430L,            122010L,                  7000L,
                "Maíz", "2018/19", "LA PAMPA",      "RANCUL",                59000L,                 32700L,            294300L,                  9000L,
                "Maíz", "2019/20", "LA PAMPA",      "RANCUL",                59700L,                 35814L,            302438L,                  8445L,
                "Maíz", "2020/21", "LA PAMPA",      "RANCUL",                65100L,                 44100L,            299880L,                  6800L,
                "Maíz", "2021/22", "LA PAMPA",      "RANCUL",                68100L,                 56900L,            449999L,                  7909L,
                "Maíz", "2022/23", "LA PAMPA",      "RANCUL",                73000L,                 61500L,            395445L,                  6430L,
                "Maíz", "2023/24", "LA PAMPA",      "RANCUL",                80500L,                 62000L,            426560L,                  6880L,
                "Maíz", "2014/15", "LA PAMPA",     "REALICÓ",                40800L,                 13800L,             96600L,                  7000L,
                "Maíz", "2015/16", "LA PAMPA",     "REALICÓ",                62800L,                 14860L,            130768L,                  8800L,
                "Maíz", "2016/17", "LA PAMPA",     "REALICÓ",                44800L,                  3800L,             27740L,                  7300L,
                "Maíz", "2017/18", "LA PAMPA",     "REALICÓ",                36900L,                  9220L,             64540L,                  7000L,
                "Maíz", "2018/19", "LA PAMPA",     "REALICÓ",                48000L,                 27850L,            250650L,                  9000L,
                "Maíz", "2019/20", "LA PAMPA",     "REALICÓ",                47800L,                 28236L,            251504L,                  8907L,
                "Maíz", "2020/21", "LA PAMPA",     "REALICÓ",                70900L,                 32800L,            259120L,                  7900L,
                "Maíz", "2021/22", "LA PAMPA",     "REALICÓ",                65900L,                 43700L,            366800L,                  8394L,
                "Maíz", "2022/23", "LA PAMPA",     "REALICÓ",                75200L,                 54700L,            403686L,                  7380L,
                "Maíz", "2023/24", "LA PAMPA",     "REALICÓ",                66300L,                 50500L,            396425L,                  7850L,
                "Maíz", "2014/15", "LA PAMPA",        "TOAY",                13000L,                  6000L,             19200L,                  3200L,
                "Maíz", "2015/16", "LA PAMPA",        "TOAY",                23000L,                 12210L,             46398L,                  3800L,
                "Maíz", "2016/17", "LA PAMPA",        "TOAY",                18000L,                  9500L,             34200L,                  3600L,
                "Maíz", "2017/18", "LA PAMPA",        "TOAY",                 5100L,                  2600L,              6500L,                  2500L,
                "Maíz", "2018/19", "LA PAMPA",        "TOAY",                 5000L,                   920L,              2944L,                  3200L,
                "Maíz", "2019/20", "LA PAMPA",        "TOAY",                13300L,                  3780L,             11718L,                  3100L,
                "Maíz", "2020/21", "LA PAMPA",        "TOAY",                20000L,                  6000L,             24000L,                  4000L,
                "Maíz", "2021/22", "LA PAMPA",        "TOAY",                18600L,                  2300L,              9200L,                  4000L,
                "Maíz", "2022/23", "LA PAMPA",        "TOAY",                44200L,                 13174L,             52696L,                  4000L,
                "Maíz", "2023/24", "LA PAMPA",        "TOAY",                44000L,                 12320L,             49280L,                  4000L,
                "Maíz", "2014/15", "LA PAMPA",      "TRENEL",                27800L,                  5800L,             29000L,                  5000L,
                "Maíz", "2015/16", "LA PAMPA",      "TRENEL",                48800L,                 18700L,            127160L,                  6800L,
                "Maíz", "2016/17", "LA PAMPA",      "TRENEL",                43000L,                  2000L,             14800L,                  7400L,
                "Maíz", "2017/18", "LA PAMPA",      "TRENEL",                39900L,                  6760L,             43940L,                  6500L,
                "Maíz", "2018/19", "LA PAMPA",      "TRENEL",                39000L,                 14380L,            110726L,                  7700L,
                "Maíz", "2019/20", "LA PAMPA",      "TRENEL",                38700L,                 23194L,            195024L,                  8408L,
                "Maíz", "2020/21", "LA PAMPA",      "TRENEL",                54300L,                 13800L,             81420L,                  5900L,
                "Maíz", "2021/22", "LA PAMPA",      "TRENEL",                54500L,                 33200L,            246500L,                  7425L,
                "Maíz", "2022/23", "LA PAMPA",      "TRENEL",                53900L,                 29000L,            188210L,                  6490L,
                "Maíz", "2023/24", "LA PAMPA",      "TRENEL",                52900L,                 37100L,            253022L,                  6820L,
                "Maíz", "2014/15", "LA PAMPA",     "UTRACÁN",                11000L,                  5000L,             15000L,                  3000L,
                "Maíz", "2015/16", "LA PAMPA",     "UTRACÁN",                11000L,                  4530L,             17214L,                  3800L,
                "Maíz", "2016/17", "LA PAMPA",     "UTRACÁN",                11000L,                  4500L,             11700L,                  2600L,
                "Maíz", "2017/18", "LA PAMPA",     "UTRACÁN",                 8200L,                  5470L,             10940L,                  2000L,
                "Maíz", "2018/19", "LA PAMPA",     "UTRACÁN",                 6900L,                  1150L,              2760L,                  2400L,
                "Maíz", "2019/20", "LA PAMPA",     "UTRACÁN",                 7500L,                  1050L,              2730L,                  2600L,
                "Maíz", "2020/21", "LA PAMPA",     "UTRACÁN",                 7000L,                  3000L,             10500L,                  3500L,
                "Maíz", "2021/22", "LA PAMPA",     "UTRACÁN",                12400L,                  5500L,             22000L,                  4000L,
                "Maíz", "2022/23", "LA PAMPA",     "UTRACÁN",                11000L,                  4840L,             19360L,                  4000L,
                "Maíz", "2023/24", "LA PAMPA",     "UTRACÁN",                12800L,                  5630L,             22520L,                  4000L,
                "Maní", "2019/20", "LA PAMPA",     "CATRILÓ",                  750L,                   750L,              1875L,                  2500L,
                "Maní", "2020/21", "LA PAMPA",     "CATRILÓ",                  772L,                   772L,              2316L,                  3000L,
                "Maní", "2021/22", "LA PAMPA",     "CATRILÓ",                  992L,                   992L,              3472L,                  3500L,
                "Maní", "2022/23", "LA PAMPA",     "CATRILÓ",                  677L,                   677L,               948L,                  1400L,
                "Maní", "2023/24", "LA PAMPA",     "CATRILÓ",                 1218L,                  1218L,              4872L,                  4000L,
                "Maní", "2014/15", "LA PAMPA",  "CHAPALEUFÚ",                 3800L,                  3800L,             10260L,                  2700L,
                "Maní", "2015/16", "LA PAMPA",  "CHAPALEUFÚ",                 8200L,                  7000L,             28000L,                  4000L,
                "Maní", "2016/17", "LA PAMPA",  "CHAPALEUFÚ",                 5400L,                  3800L,             12160L,                  3200L,
                "Maní", "2017/18", "LA PAMPA",  "CHAPALEUFÚ",                 2950L,                  2850L,              7980L,                  2800L,
                "Maní", "2018/19", "LA PAMPA",  "CHAPALEUFÚ",                 3500L,                  3500L,             14000L,                  4000L,
                "Maní", "2019/20", "LA PAMPA",  "CHAPALEUFÚ",                 3700L,                  3600L,             13680L,                  3800L,
                "Maní", "2020/21", "LA PAMPA",  "CHAPALEUFÚ",                 7950L,                  7850L,             23550L,                  3000L,
                "Maní", "2021/22", "LA PAMPA",  "CHAPALEUFÚ",                 6600L,                  6500L,             23100L,                  3554L,
                "Maní", "2022/23", "LA PAMPA",  "CHAPALEUFÚ",                 5000L,                  5000L,             15000L,                  3000L,
                "Maní", "2023/24", "LA PAMPA",  "CHAPALEUFÚ",                 5300L,                  5200L,             20800L,                  4000L,
                "Maní", "2015/16", "LA PAMPA",     "CONHELO",                  300L,                   300L,               900L,                  3000L,
                "Maní", "2016/17", "LA PAMPA",     "CONHELO",                  600L,                   600L,              1800L,                  3000L,
                "Maní", "2017/18", "LA PAMPA",     "CONHELO",                  260L,                   260L,               676L,                  2600L,
                "Maní", "2018/19", "LA PAMPA",     "CONHELO",                  300L,                   300L,              1200L,                  4000L,
                "Maní", "2019/20", "LA PAMPA",     "CONHELO",                  450L,                   450L,              1575L,                  3500L,
                "Maní", "2020/21", "LA PAMPA",     "CONHELO",                  700L,                   700L,              1540L,                  2200L,
                "Maní", "2021/22", "LA PAMPA",     "CONHELO",                  900L,                   900L,              2250L,                  2500L,
                "Maní", "2022/23", "LA PAMPA",     "CONHELO",                  600L,                   600L,              1200L,                  2000L,
                "Maní", "2023/24", "LA PAMPA",     "CONHELO",                  900L,                   900L,              3150L,                  3500L,
                "Maní", "2014/15", "LA PAMPA",      "MARACÓ",                 2500L,                  2500L,              6250L,                  2500L,
                "Maní", "2015/16", "LA PAMPA",      "MARACÓ",                 2500L,                  2000L,              8000L,                  4000L,
                "Maní", "2016/17", "LA PAMPA",      "MARACÓ",                 4700L,                  3800L,             12160L,                  3200L,
                "Maní", "2017/18", "LA PAMPA",      "MARACÓ",                 4310L,                  4310L,             12068L,                  2800L,
                "Maní", "2018/19", "LA PAMPA",      "MARACÓ",                 3500L,                  3500L,             14000L,                  4000L,
                "Maní", "2019/20", "LA PAMPA",      "MARACÓ",                 4600L,                  4500L,             17100L,                  3800L,
                "Maní", "2020/21", "LA PAMPA",      "MARACÓ",                 4050L,                  3950L,             11850L,                  3000L,
                "Maní", "2021/22", "LA PAMPA",      "MARACÓ",                 4600L,                  4500L,             15640L,                  3476L,
                "Maní", "2022/23", "LA PAMPA",      "MARACÓ",                 2800L,                  2800L,              8400L,                  3000L,
                "Maní", "2023/24", "LA PAMPA",      "MARACÓ",                 3200L,                  3100L,             12400L,                  4000L,
                "Maní", "2016/17", "LA PAMPA", "QUEMÚ QUEMÚ",                  350L,                   350L,              1050L,                  3000L,
                "Maní", "2017/18", "LA PAMPA", "QUEMÚ QUEMÚ",                 1570L,                  1570L,              4082L,                  2600L,
                "Maní", "2018/19", "LA PAMPA", "QUEMÚ QUEMÚ",                 3200L,                  3200L,             11840L,                  3700L,
                "Maní", "2019/20", "LA PAMPA", "QUEMÚ QUEMÚ",                 3600L,                  3500L,             12250L,                  3500L,
                "Maní", "2020/21", "LA PAMPA", "QUEMÚ QUEMÚ",                 5000L,                  5000L,             12500L,                  2500L,
                "Maní", "2021/22", "LA PAMPA", "QUEMÚ QUEMÚ",                 1500L,                  1500L,              4500L,                  3000L,
                "Maní", "2022/23", "LA PAMPA", "QUEMÚ QUEMÚ",                 4000L,                  4000L,             10000L,                  2500L,
                "Maní", "2023/24", "LA PAMPA", "QUEMÚ QUEMÚ",                 3200L,                  3200L,             12800L,                  4000L,
                "Maní", "2014/15", "LA PAMPA",      "RANCUL",                  400L,                   400L,               880L,                  2200L,
                "Maní", "2016/17", "LA PAMPA",      "RANCUL",                  500L,                   500L,              1500L,                  3000L,
                "Maní", "2017/18", "LA PAMPA",      "RANCUL",                  880L,                   880L,              2288L,                  2600L,
                "Maní", "2018/19", "LA PAMPA",      "RANCUL",                  800L,                   800L,              3040L,                  3800L,
                "Maní", "2019/20", "LA PAMPA",      "RANCUL",                  600L,                   600L,              2100L,                  3500L,
                "Maní", "2020/21", "LA PAMPA",      "RANCUL",                  800L,                   800L,              1760L,                  2200L,
                "Maní", "2021/22", "LA PAMPA",      "RANCUL",                  600L,                   600L,              1440L,                  2400L,
                "Maní", "2022/23", "LA PAMPA",      "RANCUL",                  200L,                   200L,               400L,                  2000L,
                "Maní", "2023/24", "LA PAMPA",      "RANCUL",                 2100L,                  2100L,              6300L,                  3000L,
                "Maní", "2014/15", "LA PAMPA",     "REALICÓ",                 2100L,                  2100L,              4830L,                  2300L,
                "Maní", "2015/16", "LA PAMPA",     "REALICÓ",                 3100L,                  2500L,              8750L,                  3500L,
                "Maní", "2016/17", "LA PAMPA",     "REALICÓ",                 2800L,                  2000L,              6400L,                  3200L,
                "Maní", "2017/18", "LA PAMPA",     "REALICÓ",                 1430L,                  1430L,              4004L,                  2800L,
                "Maní", "2018/19", "LA PAMPA",     "REALICÓ",                 1600L,                  1600L,              5920L,                  3700L,
                "Maní", "2019/20", "LA PAMPA",     "REALICÓ",                 1700L,                  1700L,              5950L,                  3500L,
                "Maní", "2020/21", "LA PAMPA",     "REALICÓ",                 1900L,                  1900L,              4750L,                  2500L,
                "Maní", "2021/22", "LA PAMPA",     "REALICÓ",                 3500L,                  3400L,             10200L,                  3000L,
                "Maní", "2022/23", "LA PAMPA",     "REALICÓ",                 3200L,                  3200L,              8000L,                  2500L,
                "Maní", "2023/24", "LA PAMPA",     "REALICÓ",                 2800L,                  2700L,             10800L,                  4000L,
                "Maní", "2019/20", "LA PAMPA",      "TRENEL",                  450L,                   450L,              1575L,                  3500L,
                "Maní", "2020/21", "LA PAMPA",      "TRENEL",                  200L,                   200L,               440L,                  2200L,
                "Maní", "2022/23", "LA PAMPA",      "TRENEL",                  300L,                   300L,               600L,                  2000L,
                "Maní", "2023/24", "LA PAMPA",      "TRENEL",                  200L,                   200L,               700L,                  3500L,
          "Soja total", "2014/15", "LA PAMPA",     "ATREUCÓ",                21000L,                 18800L,             35120L,                  1868L,
          "Soja total", "2015/16", "LA PAMPA",     "ATREUCÓ",                29563L,                 29563L,             77213L,                  2612L,
          "Soja total", "2016/17", "LA PAMPA",     "ATREUCÓ",                25000L,                 20900L,             54340L,                  2600L,
          "Soja total", "2017/18", "LA PAMPA",     "ATREUCÓ",                19000L,                 18500L,             45500L,                  2459L,
          "Soja total", "2018/19", "LA PAMPA",     "ATREUCÓ",                29200L,                 28500L,             87596L,                  3074L,
          "Soja total", "2019/20", "LA PAMPA",     "ATREUCÓ",                14300L,                 14300L,             28560L,                  1997L,
          "Soja total", "2020/21", "LA PAMPA",     "ATREUCÓ",                14531L,                 14531L,             32508L,                  2237L,
          "Soja total", "2021/22", "LA PAMPA",     "ATREUCÓ",                 7400L,                  7400L,             19050L,                  2574L,
          "Soja total", "2022/23", "LA PAMPA",     "ATREUCÓ",                 4900L,                  4900L,              9530L,                  1945L,
          "Soja total", "2023/24", "LA PAMPA",     "ATREUCÓ",                21400L,                 21400L,             47000L,                  2196L,
          "Soja total", "2014/15", "LA PAMPA",     "CAPITAL",                16000L,                 13800L,             24240L,                  1757L,
          "Soja total", "2015/16", "LA PAMPA",     "CAPITAL",                17500L,                 17500L,             46050L,                  2631L,
          "Soja total", "2016/17", "LA PAMPA",     "CAPITAL",                19500L,                 16200L,             47700L,                  2944L,
          "Soja total", "2017/18", "LA PAMPA",     "CAPITAL",                12500L,                 12000L,             17300L,                  1442L,
          "Soja total", "2018/19", "LA PAMPA",     "CAPITAL",                17500L,                 16000L,             40643L,                  2540L,
          "Soja total", "2019/20", "LA PAMPA",     "CAPITAL",                10900L,                 10900L,             20800L,                  1908L,
          "Soja total", "2020/21", "LA PAMPA",     "CAPITAL",                16441L,                 16441L,             26456L,                  1609L,
          "Soja total", "2021/22", "LA PAMPA",     "CAPITAL",                14600L,                 14600L,             29610L,                  2028L,
          "Soja total", "2022/23", "LA PAMPA",     "CAPITAL",                14380L,                 14380L,             25976L,                  1806L,
          "Soja total", "2023/24", "LA PAMPA",     "CAPITAL",                20200L,                 20200L,             42700L,                  2114L,
          "Soja total", "2014/15", "LA PAMPA",     "CATRILÓ",                38500L,                 36300L,             68370L,                  1883L,
          "Soja total", "2015/16", "LA PAMPA",     "CATRILÓ",                42262L,                 42262L,            124298L,                  2941L,
          "Soja total", "2016/17", "LA PAMPA",     "CATRILÓ",                41500L,                 35200L,            115320L,                  3276L,
          "Soja total", "2017/18", "LA PAMPA",     "CATRILÓ",                31500L,                 31100L,             87990L,                  2829L,
          "Soja total", "2018/19", "LA PAMPA",     "CATRILÓ",                46000L,                 44600L,            156400L,                  3507L,
          "Soja total", "2019/20", "LA PAMPA",     "CATRILÓ",                53900L,                 53900L,            128190L,                  2378L,
          "Soja total", "2020/21", "LA PAMPA",     "CATRILÓ",                37221L,                 37221L,             87413L,                  2348L,
          "Soja total", "2021/22", "LA PAMPA",     "CATRILÓ",                27000L,                 27000L,             79260L,                  2936L,
          "Soja total", "2022/23", "LA PAMPA",     "CATRILÓ",                40370L,                 40370L,             91644L,                  2270L,
          "Soja total", "2023/24", "LA PAMPA",     "CATRILÓ",                42900L,                 42900L,            105560L,                  2461L,
          "Soja total", "2014/15", "LA PAMPA",  "CHAPALEUFÚ",               106200L,                104100L,            333110L,                  3200L,
          "Soja total", "2015/16", "LA PAMPA",  "CHAPALEUFÚ",               110200L,                103300L,            409560L,                  3965L,
          "Soja total", "2016/17", "LA PAMPA",  "CHAPALEUFÚ",               100400L,                 81916L,            267713L,                  3268L,
          "Soja total", "2017/18", "LA PAMPA",  "CHAPALEUFÚ",                99300L,                 96300L,            306560L,                  3183L,
          "Soja total", "2018/19", "LA PAMPA",  "CHAPALEUFÚ",                97800L,                 94900L,            376323L,                  3965L,
          "Soja total", "2019/20", "LA PAMPA",  "CHAPALEUFÚ",                96300L,                 94400L,            372900L,                  3950L,
          "Soja total", "2020/21", "LA PAMPA",  "CHAPALEUFÚ",               101800L,                 99800L,            275810L,                  2764L,
          "Soja total", "2021/22", "LA PAMPA",  "CHAPALEUFÚ",                91500L,                 87800L,            321200L,                  3658L,
          "Soja total", "2022/23", "LA PAMPA",  "CHAPALEUFÚ",               101500L,                 96400L,            204800L,                  2124L,
          "Soja total", "2023/24", "LA PAMPA",  "CHAPALEUFÚ",               119600L,                117200L,            442080L,                  3772L,
          "Soja total", "2014/15", "LA PAMPA",     "CONHELO",                41700L,                 39600L,             83680L,                  2113L,
          "Soja total", "2015/16", "LA PAMPA",     "CONHELO",                38200L,                 36200L,            105700L,                  2920L,
          "Soja total", "2016/17", "LA PAMPA",     "CONHELO",                36100L,                 33908L,             96973L,                  2860L,
          "Soja total", "2017/18", "LA PAMPA",     "CONHELO",                24200L,                 23500L,             59940L,                  2551L,
          "Soja total", "2018/19", "LA PAMPA",     "CONHELO",                36800L,                 36000L,            101653L,                  2824L,
          "Soja total", "2019/20", "LA PAMPA",     "CONHELO",                38800L,                 38000L,            124200L,                  3268L,
          "Soja total", "2020/21", "LA PAMPA",     "CONHELO",                40200L,                 38200L,             72680L,                  1903L,
          "Soja total", "2021/22", "LA PAMPA",     "CONHELO",                34200L,                 33100L,             82380L,                  2489L,
          "Soja total", "2022/23", "LA PAMPA",     "CONHELO",                27400L,                 24900L,             38440L,                  1544L,
          "Soja total", "2023/24", "LA PAMPA",     "CONHELO",                50200L,                 47700L,            129910L,                  2723L,
          "Soja total", "2014/15", "LA PAMPA",   "GUATRACHÉ",                 1000L,                  1000L,              1100L,                  1100L,
          "Soja total", "2015/16", "LA PAMPA",   "GUATRACHÉ",                 2000L,                  2000L,              3400L,                  1700L,
          "Soja total", "2016/17", "LA PAMPA",   "GUATRACHÉ",                 2000L,                  1000L,              2000L,                  2000L,
          "Soja total", "2017/18", "LA PAMPA",   "GUATRACHÉ",                 1500L,                  1000L,               500L,                   500L,
          "Soja total", "2018/19", "LA PAMPA",   "GUATRACHÉ",                 1000L,                     0L,                 0L,                     0L,
          "Soja total", "2014/15", "LA PAMPA",      "MARACÓ",                93800L,                 91900L,            309660L,                  3370L,
          "Soja total", "2015/16", "LA PAMPA",      "MARACÓ",                92700L,                 89800L,            354580L,                  3949L,
          "Soja total", "2016/17", "LA PAMPA",      "MARACÓ",                79800L,                 69488L,            225440L,                  3244L,
          "Soja total", "2017/18", "LA PAMPA",      "MARACÓ",                71500L,                 69400L,            202600L,                  2919L,
          "Soja total", "2018/19", "LA PAMPA",      "MARACÓ",                76200L,                 73900L,            288800L,                  3908L,
          "Soja total", "2019/20", "LA PAMPA",      "MARACÓ",                81700L,                 80100L,            312200L,                  3898L,
          "Soja total", "2020/21", "LA PAMPA",      "MARACÓ",                83300L,                 81700L,            222490L,                  2723L,
          "Soja total", "2021/22", "LA PAMPA",      "MARACÓ",                58600L,                 52800L,            168720L,                  3195L,
          "Soja total", "2022/23", "LA PAMPA",      "MARACÓ",                76100L,                 72300L,            135240L,                  1871L,
          "Soja total", "2023/24", "LA PAMPA",      "MARACÓ",                92500L,                 90700L,            320000L,                  3528L,
          "Soja total", "2014/15", "LA PAMPA", "QUEMÚ QUEMÚ",                58100L,                 56900L,            177580L,                  3121L,
          "Soja total", "2015/16", "LA PAMPA", "QUEMÚ QUEMÚ",                42200L,                 40000L,            139680L,                  3492L,
          "Soja total", "2016/17", "LA PAMPA", "QUEMÚ QUEMÚ",                43100L,                 40472L,            115899L,                  2864L,
          "Soja total", "2017/18", "LA PAMPA", "QUEMÚ QUEMÚ",                37400L,                 36300L,            100860L,                  2779L,
          "Soja total", "2018/19", "LA PAMPA", "QUEMÚ QUEMÚ",                49800L,                 48800L,            167050L,                  3423L,
          "Soja total", "2019/20", "LA PAMPA", "QUEMÚ QUEMÚ",                55900L,                 54800L,            186350L,                  3401L,
          "Soja total", "2020/21", "LA PAMPA", "QUEMÚ QUEMÚ",                54200L,                 53100L,            124400L,                  2343L,
          "Soja total", "2021/22", "LA PAMPA", "QUEMÚ QUEMÚ",                30400L,                 29000L,             93100L,                  3210L,
          "Soja total", "2022/23", "LA PAMPA", "QUEMÚ QUEMÚ",                47800L,                 45500L,             79200L,                  1741L,
          "Soja total", "2023/24", "LA PAMPA", "QUEMÚ QUEMÚ",                49100L,                 48100L,            142780L,                  2968L,
          "Soja total", "2014/15", "LA PAMPA",      "RANCUL",                43000L,                 40900L,            100540L,                  2458L,
          "Soja total", "2015/16", "LA PAMPA",      "RANCUL",                80700L,                 77500L,            242330L,                  3127L,
          "Soja total", "2016/17", "LA PAMPA",      "RANCUL",                59500L,                 55668L,            145864L,                  2620L,
          "Soja total", "2017/18", "LA PAMPA",      "RANCUL",                68300L,                 66200L,            161930L,                  2446L,
          "Soja total", "2018/19", "LA PAMPA",      "RANCUL",                58000L,                 56800L,            178437L,                  3142L,
          "Soja total", "2019/20", "LA PAMPA",      "RANCUL",                66500L,                 65200L,            193300L,                  2965L,
          "Soja total", "2020/21", "LA PAMPA",      "RANCUL",                63800L,                 60600L,            118280L,                  1952L,
          "Soja total", "2021/22", "LA PAMPA",      "RANCUL",                61700L,                 58700L,            162600L,                  2770L,
          "Soja total", "2022/23", "LA PAMPA",      "RANCUL",                56200L,                 50600L,             79760L,                  1576L,
          "Soja total", "2023/24", "LA PAMPA",      "RANCUL",                72900L,                 69300L,            192200L,                  2773L,
          "Soja total", "2014/15", "LA PAMPA",     "REALICÓ",                39000L,                 37100L,             89600L,                  2415L,
          "Soja total", "2015/16", "LA PAMPA",     "REALICÓ",                47200L,                 45100L,            156330L,                  3466L,
          "Soja total", "2016/17", "LA PAMPA",     "REALICÓ",                41200L,                 33992L,             98017L,                  2884L,
          "Soja total", "2017/18", "LA PAMPA",     "REALICÓ",                35600L,                 34500L,             88780L,                  2573L,
          "Soja total", "2018/19", "LA PAMPA",     "REALICÓ",                40100L,                 38900L,            121511L,                  3124L,
          "Soja total", "2019/20", "LA PAMPA",     "REALICÓ",                53600L,                 52500L,            178550L,                  3401L,
          "Soja total", "2020/21", "LA PAMPA",     "REALICÓ",                52900L,                 51900L,            111900L,                  2156L,
          "Soja total", "2021/22", "LA PAMPA",     "REALICÓ",                44700L,                 40500L,            129210L,                  3190L,
          "Soja total", "2022/23", "LA PAMPA",     "REALICÓ",                39800L,                 35800L,             64240L,                  1794L,
          "Soja total", "2023/24", "LA PAMPA",     "REALICÓ",                48500L,                 47500L,            142340L,                  2997L,
          "Soja total", "2014/15", "LA PAMPA",        "TOAY",                 2000L,                  2000L,              2800L,                  1400L,
          "Soja total", "2015/16", "LA PAMPA",        "TOAY",                25000L,                 25000L,             73900L,                  2956L,
          "Soja total", "2016/17", "LA PAMPA",        "TOAY",                18000L,                 14200L,             36440L,                  2566L,
          "Soja total", "2017/18", "LA PAMPA",        "TOAY",                13000L,                 12400L,             14600L,                  1177L,
          "Soja total", "2018/19", "LA PAMPA",        "TOAY",                13600L,                 12600L,             23552L,                  1869L,
          "Soja total", "2019/20", "LA PAMPA",        "TOAY",                11800L,                 11800L,             19980L,                  1693L,
          "Soja total", "2020/21", "LA PAMPA",        "TOAY",                 8024L,                  8024L,             13556L,                  1689L,
          "Soja total", "2021/22", "LA PAMPA",        "TOAY",                 4700L,                  4700L,             10100L,                  2149L,
          "Soja total", "2022/23", "LA PAMPA",        "TOAY",                 3700L,                  3700L,              5350L,                  1446L,
          "Soja total", "2023/24", "LA PAMPA",        "TOAY",                 4000L,                  4000L,              5600L,                  1400L,
          "Soja total", "2014/15", "LA PAMPA",      "TRENEL",                19600L,                 18600L,             40470L,                  2176L,
          "Soja total", "2015/16", "LA PAMPA",      "TRENEL",                19700L,                 18700L,             62550L,                  3345L,
          "Soja total", "2016/17", "LA PAMPA",      "TRENEL",                19900L,                 17572L,             47084L,                  2679L,
          "Soja total", "2017/18", "LA PAMPA",      "TRENEL",                 9600L,                  9300L,             20390L,                  2192L,
          "Soja total", "2018/19", "LA PAMPA",      "TRENEL",                10600L,                 10400L,             29400L,                  2827L,
          "Soja total", "2019/20", "LA PAMPA",      "TRENEL",                16000L,                 15700L,             44100L,                  2809L,
          "Soja total", "2020/21", "LA PAMPA",      "TRENEL",                21100L,                 20600L,             38240L,                  1856L,
          "Soja total", "2021/22", "LA PAMPA",      "TRENEL",                18400L,                 17500L,             44940L,                  2568L,
          "Soja total", "2022/23", "LA PAMPA",      "TRENEL",                17900L,                 16400L,             24040L,                  1466L,
          "Soja total", "2023/24", "LA PAMPA",      "TRENEL",                19000L,                 18000L,             44400L,                  2467L,
          "Soja total", "2014/15", "LA PAMPA",     "UTRACÁN",                 5000L,                  5000L,              5500L,                  1100L,
          "Soja total", "2015/16", "LA PAMPA",     "UTRACÁN",                 6000L,                  6000L,             11700L,                  1950L,
          "Soja total", "2016/17", "LA PAMPA",     "UTRACÁN",                10000L,                  7800L,             19080L,                  2446L,
          "Soja total", "2017/18", "LA PAMPA",     "UTRACÁN",                 8000L,                  7100L,             14070L,                  1982L,
          "Soja total", "2018/19", "LA PAMPA",     "UTRACÁN",                 8000L,                  7000L,             11886L,                  1698L,
          "Soja total", "2019/20", "LA PAMPA",     "UTRACÁN",                 7000L,                  7000L,             10500L,                  1500L,
          "Soja total", "2021/22", "LA PAMPA",     "UTRACÁN",                  300L,                   300L,               540L,                  1800L,
          "Soja total", "2022/23", "LA PAMPA",     "UTRACÁN",                 1000L,                  1000L,              1200L,                  1200L,
          "Soja total", "2023/24", "LA PAMPA",     "UTRACÁN",                 1000L,                  1000L,              1200L,                  1200L,
               "Sorgo", "2014/15", "LA PAMPA",     "ATREUCÓ",                 6600L,                  3630L,              9438L,                  2600L,
               "Sorgo", "2015/16", "LA PAMPA",     "ATREUCÓ",                 6000L,                  6000L,             24000L,                  4000L,
               "Sorgo", "2016/17", "LA PAMPA",     "ATREUCÓ",                 6000L,                  4000L,             10000L,                  2500L,
               "Sorgo", "2017/18", "LA PAMPA",     "ATREUCÓ",                 7300L,                  4800L,             12000L,                  2500L,
               "Sorgo", "2018/19", "LA PAMPA",     "ATREUCÓ",                 7300L,                  3500L,              8750L,                  2500L,
               "Sorgo", "2019/20", "LA PAMPA",     "ATREUCÓ",                 4400L,                  1800L,              4860L,                  2700L,
               "Sorgo", "2020/21", "LA PAMPA",     "ATREUCÓ",                 7000L,                   100L,               350L,                  3500L,
               "Sorgo", "2021/22", "LA PAMPA",     "ATREUCÓ",                 8800L,                  1000L,              2900L,                  2900L,
               "Sorgo", "2022/23", "LA PAMPA",     "ATREUCÓ",                 2000L,                  1000L,              2200L,                  2200L,
               "Sorgo", "2023/24", "LA PAMPA",     "ATREUCÓ",                 2000L,                  1917L,              6710L,                  3500L,
               "Sorgo", "2014/15", "LA PAMPA",     "CAPITAL",                 3400L,                  1900L,              4750L,                  2500L,
               "Sorgo", "2015/16", "LA PAMPA",     "CAPITAL",                 3400L,                  3400L,             10200L,                  3000L,
               "Sorgo", "2016/17", "LA PAMPA",     "CAPITAL",                 3400L,                  1600L,              5600L,                  3500L,
               "Sorgo", "2017/18", "LA PAMPA",     "CAPITAL",                 4800L,                  3300L,              9900L,                  3000L,
               "Sorgo", "2018/19", "LA PAMPA",     "CAPITAL",                 4800L,                  1800L,              5400L,                  3000L,
               "Sorgo", "2019/20", "LA PAMPA",     "CAPITAL",                 3500L,                  1300L,              4160L,                  3200L,
               "Sorgo", "2020/21", "LA PAMPA",     "CAPITAL",                 6000L,                   920L,              1840L,                  2000L,
               "Sorgo", "2021/22", "LA PAMPA",     "CAPITAL",                 7900L,                  2000L,              4800L,                  2400L,
               "Sorgo", "2022/23", "LA PAMPA",     "CAPITAL",                 3000L,                   300L,               450L,                  1500L,
               "Sorgo", "2023/24", "LA PAMPA",     "CAPITAL",                 3000L,                   571L,              1713L,                  3000L,
               "Sorgo", "2014/15", "LA PAMPA",     "CATRILÓ",                 6600L,                  3630L,              9438L,                  2600L,
               "Sorgo", "2015/16", "LA PAMPA",     "CATRILÓ",                 6300L,                  6300L,             18900L,                  3000L,
               "Sorgo", "2016/17", "LA PAMPA",     "CATRILÓ",                 6300L,                  5900L,             26550L,                  4500L,
               "Sorgo", "2017/18", "LA PAMPA",     "CATRILÓ",                10800L,                  6800L,             23800L,                  3500L,
               "Sorgo", "2018/19", "LA PAMPA",     "CATRILÓ",                 5800L,                  2800L,              9800L,                  3500L,
               "Sorgo", "2019/20", "LA PAMPA",     "CATRILÓ",                 4000L,                  2300L,              7820L,                  3400L,
               "Sorgo", "2020/21", "LA PAMPA",     "CATRILÓ",                 6500L,                     0L,                 0L,                     0L,
               "Sorgo", "2021/22", "LA PAMPA",     "CATRILÓ",                 9000L,                  2200L,              4400L,                  2000L,
               "Sorgo", "2022/23", "LA PAMPA",     "CATRILÓ",                  500L,                     0L,                 0L,                     0L,
               "Sorgo", "2023/24", "LA PAMPA",     "CATRILÓ",                  600L,                   470L,              1645L,                  3500L,
               "Sorgo", "2014/15", "LA PAMPA",  "CHAPALEUFÚ",                  500L,                   500L,              3000L,                  6000L,
               "Sorgo", "2015/16", "LA PAMPA",  "CHAPALEUFÚ",                  500L,                   500L,              2750L,                  5500L,
               "Sorgo", "2016/17", "LA PAMPA",  "CHAPALEUFÚ",                  300L,                   300L,              1350L,                  4500L,
               "Sorgo", "2017/18", "LA PAMPA",  "CHAPALEUFÚ",                  800L,                   800L,              3200L,                  4000L,
               "Sorgo", "2019/20", "LA PAMPA",  "CHAPALEUFÚ",                  400L,                   400L,              1960L,                  4900L,
               "Sorgo", "2020/21", "LA PAMPA",  "CHAPALEUFÚ",                 1450L,                  1450L,              5075L,                  3500L,
               "Sorgo", "2021/22", "LA PAMPA",  "CHAPALEUFÚ",                 1200L,                  1200L,              4800L,                  4000L,
               "Sorgo", "2022/23", "LA PAMPA",  "CHAPALEUFÚ",                  600L,                   600L,              1800L,                  3000L,
               "Sorgo", "2023/24", "LA PAMPA",  "CHAPALEUFÚ",                 1200L,                  1200L,              6000L,                  5000L,
               "Sorgo", "2014/15", "LA PAMPA",     "CONHELO",                 3700L,                  3500L,             14000L,                  4000L,
               "Sorgo", "2015/16", "LA PAMPA",     "CONHELO",                 3700L,                  3500L,             15750L,                  4500L,
               "Sorgo", "2016/17", "LA PAMPA",     "CONHELO",                  200L,                   200L,               800L,                  4000L,
               "Sorgo", "2018/19", "LA PAMPA",     "CONHELO",                 1600L,                  1600L,              6720L,                  4200L,
               "Sorgo", "2019/20", "LA PAMPA",     "CONHELO",                 2600L,                  2600L,             12740L,                  4900L,
               "Sorgo", "2021/22", "LA PAMPA",     "CONHELO",                 5600L,                  5500L,             16500L,                  3000L,
               "Sorgo", "2023/24", "LA PAMPA",     "CONHELO",                 4400L,                  4400L,             17600L,                  4000L,
               "Sorgo", "2014/15", "LA PAMPA",   "GUATRACHÉ",                 4600L,                  2530L,              5566L,                  2200L,
               "Sorgo", "2015/16", "LA PAMPA",   "GUATRACHÉ",                 6300L,                  6300L,             18900L,                  3000L,
               "Sorgo", "2016/17", "LA PAMPA",   "GUATRACHÉ",                 6300L,                  6100L,             12200L,                  2000L,
               "Sorgo", "2017/18", "LA PAMPA",   "GUATRACHÉ",                12580L,                  8080L,             16160L,                  2000L,
               "Sorgo", "2018/19", "LA PAMPA",   "GUATRACHÉ",                10500L,                  2500L,              5000L,                  2000L,
               "Sorgo", "2019/20", "LA PAMPA",   "GUATRACHÉ",                 5500L,                  2100L,              4620L,                  2200L,
               "Sorgo", "2020/21", "LA PAMPA",   "GUATRACHÉ",                 9500L,                   500L,              1000L,                  2000L,
               "Sorgo", "2021/22", "LA PAMPA",   "GUATRACHÉ",                12500L,                  3000L,              5400L,                  1800L,
               "Sorgo", "2022/23", "LA PAMPA",   "GUATRACHÉ",                 1000L,                     0L,                 0L,                     0L,
               "Sorgo", "2023/24", "LA PAMPA",   "GUATRACHÉ",                 1000L,                   900L,              2700L,                  3000L,
               "Sorgo", "2014/15", "LA PAMPA",       "HUCAL",                  700L,                   400L,               880L,                  2200L,
               "Sorgo", "2015/16", "LA PAMPA",       "HUCAL",                  700L,                   700L,              2100L,                  3000L,
               "Sorgo", "2016/17", "LA PAMPA",       "HUCAL",                  700L,                   700L,              1400L,                  2000L,
               "Sorgo", "2017/18", "LA PAMPA",       "HUCAL",                 2760L,                  1260L,              2520L,                  2000L,
               "Sorgo", "2018/19", "LA PAMPA",       "HUCAL",                 2760L,                  1000L,              2000L,                  2000L,
               "Sorgo", "2019/20", "LA PAMPA",       "HUCAL",                 1300L,                   600L,              1320L,                  2200L,
               "Sorgo", "2020/21", "LA PAMPA",       "HUCAL",                 2500L,                   250L,               500L,                  2000L,
               "Sorgo", "2021/22", "LA PAMPA",       "HUCAL",                 3000L,                   700L,              1260L,                  1800L,
               "Sorgo", "2022/23", "LA PAMPA",       "HUCAL",                 3000L,                   500L,               500L,                  1000L,
               "Sorgo", "2023/24", "LA PAMPA",       "HUCAL",                 3000L,                   751L,              2253L,                  3000L,
               "Sorgo", "2014/15", "LA PAMPA",      "MARACÓ",                 1300L,                  1300L,              7800L,                  6000L,
               "Sorgo", "2015/16", "LA PAMPA",      "MARACÓ",                 1300L,                  1300L,              7150L,                  5500L,
               "Sorgo", "2016/17", "LA PAMPA",      "MARACÓ",                  200L,                   200L,               800L,                  4000L,
               "Sorgo", "2019/20", "LA PAMPA",      "MARACÓ",                 1000L,                  1000L,              4900L,                  4900L,
               "Sorgo", "2020/21", "LA PAMPA",      "MARACÓ",                 2000L,                  2000L,              7000L,                  3500L,
               "Sorgo", "2021/22", "LA PAMPA",      "MARACÓ",                  200L,                   200L,               800L,                  4000L,
               "Sorgo", "2022/23", "LA PAMPA",      "MARACÓ",                  700L,                   700L,              2100L,                  3000L,
               "Sorgo", "2023/24", "LA PAMPA",      "MARACÓ",                  800L,                   800L,              4000L,                  5000L,
               "Sorgo", "2014/15", "LA PAMPA", "QUEMÚ QUEMÚ",                  300L,                   300L,              1500L,                  5000L,
               "Sorgo", "2015/16", "LA PAMPA", "QUEMÚ QUEMÚ",                  300L,                   300L,              1500L,                  5000L,
               "Sorgo", "2016/17", "LA PAMPA", "QUEMÚ QUEMÚ",                  200L,                   200L,               800L,                  4000L,
               "Sorgo", "2018/19", "LA PAMPA", "QUEMÚ QUEMÚ",                  600L,                   600L,              2700L,                  4500L,
               "Sorgo", "2019/20", "LA PAMPA", "QUEMÚ QUEMÚ",                  700L,                   700L,              3430L,                  4900L,
               "Sorgo", "2021/22", "LA PAMPA", "QUEMÚ QUEMÚ",                 1500L,                  1500L,              5250L,                  3500L,
               "Sorgo", "2014/15", "LA PAMPA",      "RANCUL",                 2000L,                  1900L,              7600L,                  4000L,
               "Sorgo", "2015/16", "LA PAMPA",      "RANCUL",                 2000L,                  1900L,             10450L,                  5500L,
               "Sorgo", "2016/17", "LA PAMPA",      "RANCUL",                 2200L,                  2100L,              9450L,                  4500L,
               "Sorgo", "2017/18", "LA PAMPA",      "RANCUL",                  800L,                   800L,              3200L,                  4000L,
               "Sorgo", "2018/19", "LA PAMPA",      "RANCUL",                  400L,                   400L,              1800L,                  4500L,
               "Sorgo", "2019/20", "LA PAMPA",      "RANCUL",                 1400L,                  1400L,              6860L,                  4900L,
               "Sorgo", "2021/22", "LA PAMPA",      "RANCUL",                 4300L,                  4200L,             12600L,                  3000L,
               "Sorgo", "2014/15", "LA PAMPA",     "REALICÓ",                 3800L,                  3600L,             18000L,                  5000L,
               "Sorgo", "2015/16", "LA PAMPA",     "REALICÓ",                 3800L,                  3600L,             16200L,                  4500L,
               "Sorgo", "2016/17", "LA PAMPA",     "REALICÓ",                  200L,                   200L,               800L,                  4000L,
               "Sorgo", "2019/20", "LA PAMPA",     "REALICÓ",                 1400L,                  1400L,              6860L,                  4900L,
               "Sorgo", "2021/22", "LA PAMPA",     "REALICÓ",                 1500L,                  1500L,              5250L,                  3500L,
               "Sorgo", "2023/24", "LA PAMPA",     "REALICÓ",                 1000L,                  1000L,              4500L,                  4500L,
               "Sorgo", "2014/15", "LA PAMPA",        "TOAY",                 3300L,                  1800L,              4320L,                  2400L,
               "Sorgo", "2015/16", "LA PAMPA",        "TOAY",                 3300L,                  3300L,              9900L,                  3000L,
               "Sorgo", "2016/17", "LA PAMPA",        "TOAY",                 3300L,                  2300L,              4600L,                  2000L,
               "Sorgo", "2017/18", "LA PAMPA",        "TOAY",                 5500L,                  4000L,              8000L,                  2000L,
               "Sorgo", "2018/19", "LA PAMPA",        "TOAY",                 5500L,                  2000L,              4000L,                  2000L,
               "Sorgo", "2019/20", "LA PAMPA",        "TOAY",                 2700L,                  1200L,              2640L,                  2200L,
               "Sorgo", "2020/21", "LA PAMPA",        "TOAY",                 4900L,                  1500L,              4800L,                  3200L,
               "Sorgo", "2021/22", "LA PAMPA",        "TOAY",                 6000L,                  2000L,              3800L,                  1900L,
               "Sorgo", "2022/23", "LA PAMPA",        "TOAY",                 3000L,                   500L,               500L,                  1000L,
               "Sorgo", "2023/24", "LA PAMPA",        "TOAY",                 3000L,                  1413L,              4946L,                  3500L,
               "Sorgo", "2014/15", "LA PAMPA",      "TRENEL",                 1100L,                  1000L,              4000L,                  4000L,
               "Sorgo", "2015/16", "LA PAMPA",      "TRENEL",                 1100L,                  1000L,              6000L,                  6000L,
               "Sorgo", "2016/17", "LA PAMPA",      "TRENEL",                  600L,                   600L,              2400L,                  4000L,
               "Sorgo", "2018/19", "LA PAMPA",      "TRENEL",                  600L,                   600L,              2400L,                  4000L,
               "Sorgo", "2019/20", "LA PAMPA",      "TRENEL",                  700L,                   700L,              3080L,                  4400L,
               "Sorgo", "2021/22", "LA PAMPA",      "TRENEL",                  300L,                   300L,               900L,                  3000L,
               "Sorgo", "2022/23", "LA PAMPA",      "TRENEL",                  400L,                   400L,              1200L,                  3000L,
               "Sorgo", "2023/24", "LA PAMPA",      "TRENEL",                  900L,                   900L,              3600L,                  4000L,
               "Sorgo", "2014/15", "LA PAMPA",     "UTRACÁN",                 2000L,                  1100L,              2530L,                  2300L,
               "Sorgo", "2015/16", "LA PAMPA",     "UTRACÁN",                 2000L,                  2000L,              6000L,                  3000L,
               "Sorgo", "2016/17", "LA PAMPA",     "UTRACÁN",                 2000L,                  2000L,              4400L,                  2200L,
               "Sorgo", "2017/18", "LA PAMPA",     "UTRACÁN",                 3560L,                  2060L,              4532L,                  2200L,
               "Sorgo", "2018/19", "LA PAMPA",     "UTRACÁN",                 3560L,                  1560L,              3120L,                  2000L,
               "Sorgo", "2019/20", "LA PAMPA",     "UTRACÁN",                 1700L,                   800L,              1760L,                  2200L,
               "Sorgo", "2020/21", "LA PAMPA",     "UTRACÁN",                 2900L,                   840L,              2520L,                  3000L,
               "Sorgo", "2021/22", "LA PAMPA",     "UTRACÁN",                 3800L,                  1500L,              2250L,                  1500L,
               "Sorgo", "2022/23", "LA PAMPA",     "UTRACÁN",                 2000L,                   500L,               750L,                  1500L,
               "Sorgo", "2023/24", "LA PAMPA",     "UTRACÁN",                 2000L,                   658L,              1974L,                  3000L
          )

```

```{r}
gruesa$Cultivo<-as.factor(gruesa$Cultivo)
```

```{r}
levels(gruesa$Cultivo)
```


```{r}
resumen_maiz<-gruesa %>% filter(Cultivo=="Maíz") %>%pull(Rendimiento_KgHa) %>% 
  summary()
# pull extrae una columna
resumen_maiz
```

